#!/usr/bin/env python3
"""Render README.md and docs/*.md from the YAML sources.

The YAML files are the single source of truth. Every markdown table in this repo is
generated, so a paper's metadata can never disagree between two tables.
"""
import re
from collections import Counter, defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DOCS = ROOT / "docs"

TASK_LABEL = {
    "image-recon": "Image reconstruction",
    "video-recon": "Video reconstruction",
    "image-retrieval": "Image retrieval / identification",
    "captioning": "Brain captioning",
    "language-recon": "Continuous language reconstruction",
    "speech-decoding": "Speech decoding",
    "text-decoding": "Brain-to-text",
    "representation": "Representation / encoding analyses",
    "eval": "Evaluation, replication and critique",
    "survey": "Surveys and taxonomies",
}
GEN = "<!-- generated by scripts/build.py -- edit data/*.yaml instead -->"

CFG = yaml.safe_load((DATA / "config.yaml").read_text())
HL = CFG.get("highlight", {})
RELEASES = sorted(CFG.get("releases", []), key=lambda r: str(r["date"]))
LAST_RELEASE = str(RELEASES[-1]["date"]) if RELEASES else "0000-00-00"


def is_new(p):
    """Added after the most recent release, i.e. part of the delta a returning reader wants."""
    return str(p.get("added", "0000-00-00")) > LAST_RELEASE


def highlight(text, new):
    """GitHub sanitises CSS out of README.md, so a literal coloured row background is not
    available. <mark> is on GitHub's tag allowlist and does render a real background
    highlight; the badge route trades the background for exact colour control."""
    if not new or HL.get("style") in (None, "none"):
        return text
    if HL["style"] in ("mark", "both"):
        text = f"<mark>{text}</mark>"
    return text


def new_badge(p):
    if not is_new(p) or HL.get("style") not in ("badge", "both"):
        return ""
    label = HL.get("new_label", "new")
    color = HL.get("badge_color", "FFD1DC")
    return f" ![{label}](https://img.shields.io/badge/{label}-{color}?style=flat-square&labelColor={color})"


def load(name):
    return yaml.safe_load((DATA / name).read_text())


_VENUE_PATTERNS = [(re.compile(pat, re.I), short, add_year)
                   for pat, short, add_year in load("venues.yaml")["patterns"]]


def short_venue(p):
    """Crossref returns series titles like 'Lecture Notes in Computer Science'. Map them
    to what a reader actually wants to see, with a per-paper override winning."""
    if p.get("venue_short"):
        return p["venue_short"]
    v = p.get("venue")
    if not v:
        return "—"
    for rx, short, add_year in _VENUE_PATTERNS:
        if rx.search(v):
            return f"{short} {p['year']}" if add_year else short
    return v if len(v) <= 34 else v[:31] + "…"


def paper_row(p, ds_by_id):
    title = p["title"]
    link = p.get("paper")
    cell = f"[{title}]({link})" if link else f"{title} ⚠️"
    new = is_new(p)
    cell = highlight(cell, new)
    code = f"[code]({p['code']})" if p.get("code") else "—"
    venue = short_venue(p)
    mod = "/".join(p.get("modality", []))
    dsets = ", ".join(ds_by_id.get(d, {}).get("short", d) for d in p.get("datasets", []) or []) or "—"
    flags = " ".join(f"`{f}`" for f in p.get("flags", []) or []) or ""
    return f"| {p['year']}{new_badge(p)} | {cell} {flags} | {mod} | {venue} | {dsets} | {code} |"


def papers_section(papers, ds_by_id):
    by_task = defaultdict(list)
    for p in papers:
        for t in p.get("task", []):
            by_task[t].append(p)
    out = []
    for task in TASK_LABEL:
        rows = sorted(by_task.get(task, []), key=lambda p: (-p["year"], p["title"]))
        if not rows:
            continue
        out.append(f"\n### {TASK_LABEL[task]}  <sub>({len(rows)})</sub>\n")
        out.append("| Year | Paper | Modality | Venue | Data | Code |")
        out.append("|---|---|---|---|---|---|")
        out += [paper_row(p, ds_by_id) for p in rows]
    return "\n".join(out)


def datasets_doc(datasets):
    lines = [GEN, "# Datasets", "",
             "The column that matters most is **per subject**: it is the budget every decoder",
             "is actually spending, and it is the column most comparison tables omit.", ""]
    for domain, title in (("vision", "Vision"), ("language", "Language")):
        rows = [d for d in datasets if d.get("domain") == domain]
        lines += [f"## {title}", "",
                  "| Dataset | Modality | Subjects | Per subject | Access | Verified |",
                  "|---|---|---|---|---|---|"]
        for d in rows:
            dep = " ⛔️" if d.get("status") == "deprecated" else ""
            name = f"[{d['name']}]({d['url']})" if d.get("url") else d["name"]
            lines.append(
                f"| {name}{dep} | {'/'.join(d['modality'])} | {d.get('subjects','—')} | "
                f"{d.get('per_subject','—')} | {d.get('access','—')} | "
                f"{'✅' if d.get('verified') else '⚠️'} |")
        lines.append("")
    lines += ["## Caveats", "",
              "Each of these will silently change a number by more than most methods claim to gain.", ""]
    for d in datasets:
        if d.get("caveats"):
            lines.append(f"**{d['name']}**")
            lines += [f"- {c}" for c in d["caveats"]]
            lines.append("")
    return "\n".join(lines)


def pitfalls_doc(pitfalls):
    lines = [GEN, "# Evaluation pitfalls", "",
             "A number in a paper is only comparable to another number if both survived the",
             "checks below. Each entry names the work that established it and gives a test you",
             "can run in an afternoon.", ""]
    for p in pitfalls:
        if "id" not in p:
            continue
        lines += [f"## `{p['id']}` — {p['name']}", "",
                  f"**Applies to:** {'/'.join(p['applies_to'])}", "",
                  f"**What happens.** {p['what'].strip()}", "",
                  f"**Why it breaks comparison.** {p['consequence'].strip()}", ""]
        if p.get("established_by"):
            lines += [f"**Established by:** `{p['established_by']}`", ""]
        lines += [f"**How to check.** {p['how_to_check']}", "", "---", ""]
    return "\n".join(lines)


def repro_doc(papers):
    lines = [GEN, "# Reproducibility status", "",
             "`ran-ok` and `ran-mismatch` are only set by a human who actually ran the code and",
             "says so in the PR. Everything else is `claimed` or `none`.", "",
             "| Paper | Code | Weights | Status | Notes |", "|---|---|---|---|---|"]
    for p in sorted([x for x in papers if x.get("code")], key=lambda p: -p["year"]):
        lines.append(
            f"| {p['title'][:60]} | [repo]({p['code']}) | "
            f"{'✅' if p.get('weights') else '—'} | `{p.get('repro','claimed')}` | {p.get('repro_notes','')} |")
    return "\n".join(lines)


def benchmarks_doc(papers, ds_by_id):
    lines = [GEN, "# Benchmark tables", "",
             "**Read [pitfalls.md](pitfalls.md) before reading any number here.**", "",
             "Cells are only filled once someone has recorded the split, the retrieval pool size",
             "and the per-subject data budget alongside the number. A metric without those three",
             "is not a comparable metric, so it is left empty rather than shown.", ""]
    have = [p for p in papers if p.get("metrics")]
    if not have:
        lines += ["> Status: schema is in place, no cells verified yet. See `data/papers.yaml`",
                  "> field `metrics:` and CONTRIBUTING.md for the contract.", ""]
    for p in have:
        for m in p["metrics"]:
            lines.append(f"- {p['title']} — {m}")
    return "\n".join(lines)


def whats_new_section(papers, ds_by_id):
    """A one-line banner, not a second copy of the rows.

    An earlier version rendered a full table of the new entries above the main tables.
    That duplicated every row: the same paper appeared twice on one page, once in the
    summary and once highlighted in place. The highlight already answers "which are new";
    the banner only needs to answer "how many, and since when".
    """
    fresh = [p for p in papers if is_new(p)]
    if not fresh:
        return ""
    last = RELEASES[-1] if RELEASES else {}
    day = LAST_RELEASE.split("T")[0]
    n = len(fresh)
    return (f"> [!NOTE]\n"
            f"> **{n} new {'entry' if n == 1 else 'entries'} since {last.get('version', 'the last release')}** "
            f"({day}), highlighted in the tables below. "
            f"Full history in [CHANGELOG.md](CHANGELOG.md).\n\n---\n")


def changelog(papers):
    lines = [GEN, "# Changelog", "",
             "Releases are cut by `scripts/release.py`, which appends to `releases:` in",
             "`data/config.yaml`. Everything added after the newest release date is rendered",
             "as new in the README until the next release rolls the window forward.", ""]
    bounds = [str(r["date"]) for r in RELEASES]
    for i, r in enumerate(reversed(RELEASES)):
        lo = bounds[len(RELEASES) - i - 2] if len(RELEASES) - i - 2 >= 0 else "0000-00-00"
        hi = str(r["date"])
        added = [p for p in papers if lo < str(p.get("added", "")) <= hi]
        lines += [f"## {r['version']} — {hi}", ""]
        if r.get("note"):
            lines += [f"_{r['note']}_", ""]
        lines += [f"{len(added)} entries added.", ""]
        for p in sorted(added, key=lambda p: p["title"]):
            link = p.get("paper")
            lines.append(f"- {'[' + p['title'] + '](' + link + ')' if link else p['title']}")
        lines.append("")
    pending = [p for p in papers if is_new(p)]
    if pending:
        lines = lines[:4] + [f"## Unreleased  <sub>({len(pending)} entries)</sub>", ""] + \
                [f"- {p['title']}" for p in sorted(pending, key=lambda p: p['title'])] + [""] + lines[4:]
    return "\n".join(lines)


def readme(papers, datasets, pitfalls):
    n = len(papers)
    mods = Counter(m for p in papers for m in p.get("modality", []))
    unresolved = [p for p in papers if not p.get("paper")]
    head = (ROOT / "docs" / "_readme_head.md").read_text()
    ds_by_id = {d["id"]: {**d, "short": d["name"].split("(")[0].strip()} for d in datasets}
    body = [
        head.rstrip(), "",
        f"**{n} papers · {len(datasets)} datasets · {len([x for x in pitfalls if 'id' in x])} documented evaluation pitfalls**  ",
        f"Coverage: fMRI {mods['fMRI']} · EEG {mods['EEG']} · MEG {mods['MEG']}"
        + (f" · {len(unresolved)} entries awaiting link resolution ⚠️" if unresolved else ""),
        "",
        "| | |", "|---|---|",
        "| [Datasets](docs/datasets.md) | what each corpus actually contains, and the per-subject budget it gives you |",
        "| [Pitfalls](docs/pitfalls.md) | the confounds that make published numbers incomparable, with a test for each |",
        "| [Benchmarks](docs/benchmarks.md) | metrics, reported only with split, pool size and data budget attached |",
        "| [Reproducibility](docs/reproducibility.md) | which released code has actually been run by someone |",
        "", "---", "", whats_new_section(papers, ds_by_id), "## Papers",
        papers_section(papers, ds_by_id), "", "---", "",
        (ROOT / "docs" / "_readme_tail.md").read_text().rstrip(), "",
    ]
    return "\n".join(body)


def main():
    papers = [p for p in load("papers.yaml") if isinstance(p, dict) and "title" in p]
    datasets = load("datasets.yaml")
    pitfalls = load("pitfalls.yaml")
    ds_by_id = {d["id"]: {**d, "short": d["name"].split("(")[0].strip()} for d in datasets}

    (DOCS / "datasets.md").write_text(datasets_doc(datasets))
    (DOCS / "pitfalls.md").write_text(pitfalls_doc(pitfalls))
    (DOCS / "reproducibility.md").write_text(repro_doc(papers))
    (DOCS / "benchmarks.md").write_text(benchmarks_doc(papers, ds_by_id))
    (ROOT / "README.md").write_text(readme(papers, datasets, pitfalls))
    (ROOT / "CHANGELOG.md").write_text(changelog(papers))

    # sanity checks -- fail loudly rather than shipping a broken table
    known = set(ds_by_id)
    bad = [(p["key"], d) for p in papers for d in (p.get("datasets") or []) if d not in known]
    if bad:
        raise SystemExit(f"unknown dataset ids referenced: {bad}")
    known_flags = {x["id"] for x in pitfalls if "id" in x}
    badf = [(p["key"], f) for p in papers for f in (p.get("flags") or []) if f not in known_flags]
    if badf:
        raise SystemExit(f"unknown pitfall ids referenced: {badf}")
    print(f"built: {len(papers)} papers, {len(datasets)} datasets, {len(known_flags)} pitfalls")
    miss = [p["key"] for p in papers if not p.get("paper")]
    if miss:
        print(f"warning: {len(miss)} papers still without a resolved link: {', '.join(miss)}")


if __name__ == "__main__":
    main()
